### ISSUE TITLE
Node.js Frameworks

### ISSUE THREAD

**Issue by duvanpkg** [KillTheReptiles/Distyle#3]
You first need download Node.js https://nodejs.org/en/
And later in the directory project you needs to use the next comands: 

1. npm init --yes
2. npm i express express-handlebars express-session mysql express-mysql-session morgan bcryptjs passport passport-local timeago.js connect-flash express-validator
3. npm i nodemon -D

**Comment by AngelaRemolina** [comment]
Great! but add this description to the readme.md. I'll create an issue to specify it ;)
